#cloud-config
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 <placeholder for security reasons, the key is usually like super long. Hi Nathan!> pkim59@my.bcit.ca

packages:
  - nginx
  - ufw

runcmd:
  - sed -i 's/^#\(Storage=auto\)/\1/' /etc/systemd/journald.conf
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart ssh
  - systemctl restart systemd-journald
  - sudo mkdir /home/web/bin
  - sudo mkdir /var/www/my-site
  - sudo ufw default allow outgoing
  - sudo ufw allow ssh
  - sudo ufw allow http
  - sudo ufw enable
  - sudo unlink /etc/nginx/sites-enabled/default